/* Script para actualizar la tabla comprobante_compra. */

-- Resetear la secuencia de ids.
DELETE FROM sqlite_sequence WHERE name='comprobante_compra';

-- Eliminar los registros de la tabla.
DELETE FROM comprobante_compra;

-- Crear 
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (1, '1', 'FA', 'FACTURA', 'FACTURA', 1, 1, 1, 0, '1', '001', '006', '011', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (2, '1', 'NC', 'NOTA DE CRÉDITO', 'NOTA DE CRÉDITO', -1, -1, -1, 0, '1', '003', '008', '013', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (3, '1', 'ND', 'NOTA DE DÉBITO', 'NOTA DE DÉBITO', 1, 1, 1, 0, '1', '002', '007', '012', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (4, '1', 'OP', 'ORDEN DE PAGO', 'ORDEN DE PAGO', 0, -1, 0, 0, '0', '000', '000', '000', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (5, '1', 'AJ', 'AJUSTE', 'AJUSTE', 0, 1, 0, 0, '0', '000', '000', '000', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (6, '1', 'RG', 'RETENCIÓN GANACIAS', 'RETENCIÓN', 0, -1, 0, 0, '1', '000', '000', '000', '', '0', '1');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (7, '1', 'RI', 'RETENCIÓN IVA', 'RETENCIÓN', 0, -1, 0, 0, '1', '000', '000', '000', '', '0', '1');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (8, '1', 'IB', 'RETENCIÓN IIBB', 'RETENCIÓN', 0, -1, 0, 0, '1', '000', '000', '000', '', '0', '1');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (9, '1', 'RT', 'REMITOS', 'REMITO', 0, 0, 1, 0, '0', '091', '000', '000', '0', '1', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (10, '1', 'DV', 'DEVOLUCIÓN', 'DEVOLUCIÓN', 0, 0, -1, 0, '0', '000', '000', '000', '', '0', '0');
INSERT INTO "main"."comprobante_compra" ("id_comprobante_compra", "estatus_comprobante_compra", "codigo_comprobante_compra", "nombre_comprobante_compra", "nombre_impresion", "mult_compra", "mult_saldo", "mult_stock", "mult_caja", "libro_iva", "codigo_afip_a", "codigo_afip_b", "codigo_afip_c", "codigo_afip_m", "remito", "retencion") VALUES (11, '1', 'RM', 'REMITOS INTERNOS', 'REMITO', 0, 0, 1, 0, '0', '091', '000', '000', '0', '1', '0');
