-- ============================================
-- LIMPIEZA Y RESETEO DE SECUENCIA
-- ============================================

-- Eliminar todos los registros
DELETE FROM comprobante_venta;

-- Resetear la secuencia en PostgreSQL
SELECT setval(pg_get_serial_sequence('comprobante_venta', 'id_comprobante_venta'), 1, false);

-- ============================================
-- INSERCIÓN DE DATOS (manteniendo IDs manuales)
-- ============================================

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 1, TRUE, 'FA', 'FACTURA', 'FACTURA', '1', NULL, 1, 1, -1, 1, 1, 1, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, '001', '006', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 2, TRUE, 'NC', 'N.DE CREDITO', 'NOTA DE CRÉDITO', '1', 'FA, MF, ND', -1, -1, 1, -1, -1, -1, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, '003', '008', FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 3, FALSE, 'ND', 'N.DE DEBITO', 'NOTA DE DÉBITO', '1', 'FA, MF', 1, 1, -1, 1, 1, 0, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, '002', '007', FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 4, TRUE, 'RB', 'RECIBO', 'RECIBO', '2', NULL, 1, -1, 0, 0, 1, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RB', 'RB', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 5, TRUE, 'AJ', 'AJUSTE', 'AJUSTE', '2', NULL, 1, 1, 0, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 'AJ', 'AJ', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 6, TRUE, 'MI', 'MOVIMIENTO INTERNO', 'MOVIMIENTO INTERNO', '2', NULL, 0, 0, 1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'MI', 'MI', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 7, TRUE, 'PR', 'PRESUPUESTO', 'PRESUPUESTO', '2', NULL, 0, 0, 0, 0, 0, 0, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 'PR', 'PR', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 8, TRUE, 'FF', 'FACTURA ELECTRONICA', 'FACTURA', '3', NULL, 1, 1, -1, 1, 1, 1, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, '001', '006', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 9, TRUE, 'CF', 'NOTA DE CREDITO ELEC', 'NOTA DE CRÉDITO', '3', 'FF, FR, DF', -1, -1, 1, -1, -1, -1, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, '003', '008', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 10, TRUE, 'DF', 'NOTA DE DEBITO ELECT', 'NOTA DE DÉBITO', '3', 'FF, FR', 1, 1, -1, 0, 1, 0, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, '002', '007', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 11, TRUE, 'RF', 'REMITO', 'REMITO', '2', NULL, 0, 0, -1, 0, 0, 1, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, '091', '091', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 12, TRUE, 'RD', 'REMITO DEVOLUCION', 'REMITO', '2', 'RF', 0, 0, 1, 0, 0, -1, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, '091', '091', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES ('admin', 'Leoncio', '2026-04-23 11:06:34', 13, TRUE, 'FR', 'FACTURA REMITO', 'FACTURA', NULL, 'RF, RT', 1, 1, 0, 1, 1, 0, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, '001', '006', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 14, FALSE, 'RT', 'REMITO MANUAL', 'REMITO', '1', NULL, 0, 0, -1, 0, 0, -1, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, '091', '091', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 15, TRUE, 'RR', 'RECIBO SIN COMISION', 'RECIBO', '2', NULL, 1, -1, 0, 0, 1, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RB', 'RB', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 16, TRUE, 'RM', 'REMITO INTERNO', 'REMITO', '2', NULL, 0, 0, -1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '091', '091', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 17, TRUE, 'DM', 'REMITO INTERNO DEVOL', 'REMITO', '2', 'RM', 0, 0, 1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, '091', '091', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 18, TRUE, 'MR', 'REMITO INT.MANUAL', 'REMITO', '2', NULL, 0, 0, -1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '091', '091', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 19, TRUE, 'MD', 'REMITO DEV.MANUAL', 'REMITO', '2', 'RT', 0, 0, 1, 0, 0, -1, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, '091', '091', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 20, FALSE, 'MF', 'FACTURA RTO.MANUAL', 'FACTURA', '1', 'RT', 1, 1, 0, 0, 1, 0, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, '001', '006', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 21, FALSE, 'RC', 'RECIBO - CAMION -', 'RECIBO', '2', NULL, 1, -1, 0, 0, 1, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RB', 'RB', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 22, TRUE, 'MS', 'REMITO INT.DEV.MANUA', 'REMITO', '2', 'MR', 0, 0, 1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '091', '091', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 23, TRUE, 'EG', 'EGRESOS DE CAJA', 'EGRESOS DE CAJA', '2', NULL, 0, 0, 0, 0, -1, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'EG', 'EG', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 24, TRUE, 'RE', 'RECIBO MANUAL', 'RECIBO', '2', NULL, 1, -1, 0, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RE', 'RE', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 25, TRUE, 'IN', 'INGRESOS DE CAJA', 'INGRESO DE CAJA', '2', NULL, 0, 0, 0, 0, 1, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'IN', 'IN', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 26, TRUE, 'RS', 'RECIBO MANUAL S/COMI', 'RECIBO', '2', NULL, 1, -1, 0, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RE', 'RE', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 27, TRUE, 'FC', 'FCE - FACTURA CREDITO MIPYME', 'FACTURA', '3', NULL, 1, 1, -1, 1, 1, 1, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, '201', '206', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 28, TRUE, 'CE', 'FCE - N.CREDITO MIPYME', 'NOTA DE CRÉDITO', '3', 'FC, FT, DE', -1, -1, 1, -1, -1, -1, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, '203', '208', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 29, TRUE, 'DE', 'FCE - N.DEBITO MIPYME', 'NOTA DE DÉBITO', '3', 'FC, FT', 1, 1, -1, 0, 1, 0, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, '202', '207', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 30, TRUE, 'FT', 'FCE - FACTURA/RTO MIPYME', 'FACTURA', '3', 'RF, RT', 1, 1, 0, 1, 1, 0, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, '201', '206', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 31, TRUE, 'MM', 'REMITO DE MICHELIN', 'REMITO', NULL, NULL, 0, 0, -1, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '091', '091', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);

INSERT INTO comprobante_venta (usuario, estacion, fcontrol, id_comprobante_venta, estatus_comprobante_venta, codigo_comprobante_venta, nombre_comprobante_venta, tipo_comprobante, tipo_numeracion, compro_asociado, mult_venta, mult_saldo, mult_stock, mult_comision, mult_caja, mult_estadistica, libro_iva, estadistica, electronica, presupuesto, pendiente, info_michelin_auto, info_michelin_camion, codigo_afip_a, codigo_afip_b, remito, recibo, ncr_ndb, manual, mipyme, interno, id_user_id) VALUES (NULL, NULL, NULL, 32, FALSE, 'RN', 'RECIBO - CAMION - MANUAL', 'RECIBO', NULL, NULL, 1, -1, 0, 0, 0, 0, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'RE', 'RE', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 1);

-- ============================================
-- VERIFICACIÓN
-- ============================================
SELECT COUNT(*) AS total_registros FROM comprobante_venta;
SELECT * FROM comprobante_venta ORDER BY id_comprobante_venta;