* previamente se actualizaron los id de compras vs detcom con act_detcom
CLOSE DATABASES
CLEAR ALL

USE COMPRAS IN 0
USE DETCOM IN 0 ORDER ID

* ELMINAR DETALLE DE COMPRAS
* fecha < {^2024-01-01} or EMPTY(fecha)
SELECT COMPRAS
SET FILTER TO fecha < {^2024-01-01} or EMPTY(fecha)
GO top
DO WHILE !EOF()
	SCATTER MEMVAR FIELDS ID
	
	SELECT DETCOM
	SET KEY TO m.ID
	GO TOP
	IF !EOF()
		WAIT WINDOW m.ID NOWAIT
		DELETE FOR ID = m.ID
	ENDIF
	
	SELECT COMPRAS
	IF !EOF()
		SKIP
	ENDIF
ENDDO

SELECT DETCOM
GO TOP
PACK

SELECT COMPRAS
DELETE FOR fecha < {^2024-01-01} or EMPTY(fecha)
PACK


