CLOSE DATABASES
CLEAR ALL
SET EXCLUSIVE ON


******************
* TABLA OPERARIO *
******************
USE OPERARIO IN 0
SELECT OPERARIO
DELETE FOR EMPTY(CODIGO)
PACK
SELECT OPERARIO
USE

***************
* TABLA STOCK *
***************
USE STOCK IN 0
SELECT STOCK
DELETE FOR EMPTY(DEPOSITO)
PACK
SELECT STOCK
USE

*****************
* TABLA CLINTES *
*****************
USE CLIENTES IN 0
SELECT CLIENTES
DELETE FOR EMPTY(NOMBRE)
PACK
SELECT CLIENTES
USE

*********************************************
* TABLA STOCKCLIENTE Y AGREGADO DE FACTURAS *
*********************************************
USE FACTURAS IN 0 ORDER ID
USE DETVEN IN 0
USE STOCKCLIENTE IN 0

USE D:\MAAS\DEBONA-SH\DATA\FACTURAS IN 0 ALIAS FACTOLD ORDER ID
USE D:\MAAS\DEBONA-SH\DATA\DETVEN IN 0 ALIAS DETVEOLD ORDER ID

* depuracion de la tabla stockcliente
SELECT STOCKCLIENTE
DELETE FOR fecha < {^2024-01-01} and (cantidad = retirado)
PACK
GO TOP
nofind = 0
nofind2 = 0
DO WHILE !EOF()
	SCATTER MEMVAR
	
	SELECT FACTURAS
	SEEK m.id
	IF !FOUND()
		nofind = nofind + 1
		
		SELECT FACTOLD
		SEEK m.id
		IF !FOUND()
			nofind2 = nofind2 + 1
			? m.ID
		ELSE
			* INSERTAR EN LA TABLA FACTURAS
			SELECT FACTOLD
			SCATTER MEMVAR
			INSERT INTO FACTURAS FROM MEMVAR
			
			* INSERTAR EN LA TABLA DETVEN
			SELECT DETVEOLD
			SET KEY TO m.ID
			GO TOP
			SCAN
				SCATTER MEMVAR
				INSERT INTO DETVEN FROM MEMVAR
			ENDSCAN
			
		ENDIF
	
	ENDIF

	SELECT STOCKCLIENTE
	IF !EOF()
		SKIP
	ENDIF
ENDDO

? '--------------'
? 'No encontrados'
? nofind
? '--------------'
? 'No encontrados 2'
? nofind2


SELECT FACTURAS
USE
SELECT DETVEN
USE
SELECT FACTOLD
USE
SELECT DETVEOLD
USE

******************
* TABLA LISTAMIN *
******************
USE LISTAMIN IN 0
SELECT LISTAMIN
DELETE FOR cai = "9.328.11831ÿÿÿÿ"
PACK
USE

******************
* TABLA VENDEDOR *
******************
USE VENDEDOR IN 0
SELECT VENDEDOR
REPLACE CODIGO WITH 1 FOR CODIGO = 0
USE

**********************
* TABLA STOCKCLIENTE *
**********************
CLOSE TABLES ALL 
USE STOCKCLIENTE IN 0
SELECT STOCKCLIENTE
SET FILTER TO id = 1569043 AND codigo = 180000
GO top
REPLACE cantidad WITH 1
REPLACE RETIRADO WITH 1
USE

CLOSE DATABASES
CLEAR ALL

