# Generated by Django 5.1.1 on 2026-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLStockGeneralDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('otras_suc', models.IntegerField()),
                ('stock_total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock General por Depósito',
                'verbose_name_plural': 'Stock General por Depósito',
                'db_table': 'vlstockgeneraldeposito',
                'managed': False,
            },
        ),
    ]
