# Generated by Django 5.1.1 on 2026-04-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cae',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='CAE'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_comprobante',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
