# Generated by Django 5.1.1 on 2026-10-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInterno',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_movimiento_interno', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_comprobante', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('compro', models.CharField(blank=True, max_length=3, null=True, verbose_name='Compro')),
                ('letra_comprobante', models.CharField(blank=True, max_length=1, null=True, verbose_name='Letra')),
                ('numero_comprobante', models.BigIntegerField(blank=True, null=True, verbose_name='Número')),
                ('fecha_comprobante', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('observa_comprobante', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_comprobante_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comprobante')),
                ('id_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productodeposito', verbose_name='Depósito')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'Movimiento Interno',
                'verbose_name_plural': 'Movimientos Internos',
                'db_table': 'movimiento_interno',
                'ordering': ['id_movimiento_interno'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoInterno',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_detalle_movimiento_interno', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Cód. Producto')),
                ('producto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre producto')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Cantidad')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.producto', verbose_name='Producto')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
                ('id_movimiento_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.movimientointerno', verbose_name='Movimiento Interno')),
            ],
            options={
                'verbose_name': 'Detalle Movimiento Interno',
                'verbose_name_plural': 'Detalles Movimiento Interno',
                'db_table': 'detalle_movimiento_interno',
                'ordering': ['id_detalle_movimiento_interno'],
            },
        ),
    ]
