# Generated by Django 5.1.1 on 2026-05-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='cajadetalle',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='chequerecibo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='depositorecibo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='retencionrecibo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='serialfactura',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='stockcliente',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='tarjetarecibo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='cajadetalle',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='depositorecibo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='retencionrecibo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='serialfactura',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='stockcliente',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AlterField(
            model_name='tarjetarecibo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
    ]
