# Generated by Django 5.1.1 on 2026-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_factura_cae_alter_factura_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadetalle',
            name='idbancos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajadetalle',
            name='idcompras',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajadetalle',
            name='idventas',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='documento_asociado',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Documento Asociado'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_comprobante',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_comprobante_venta',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número C/Compra'),
        ),
    ]
