# Generated by Django 5.1.1 on 2026-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cajadetalle_idbancos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequerecibo',
            name='codigo_banco',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código Banco'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='codigo_postal',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='cuenta_cheque_recibo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='cuit_cheque_recibo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='numero_cheque_recibo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='sucursal',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='tarjetarecibo',
            name='cuotas',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Cuotas'),
        ),
        migrations.AlterField(
            model_name='tarjetarecibo',
            name='cupon',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Cupón'),
        ),
        migrations.AlterField(
            model_name='tarjetarecibo',
            name='lote',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Lote'),
        ),
    ]
