# Generated by Django 5.1.1 on 2026-07-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_valida_motivo'),
        ('ventas', '0004_caja_fcontrol2_cajadetalle_fcontrol2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='id_valida_limite_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_limite', to='maestros.valida', verbose_name='Autorización de límite de crédito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_valida_nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_nota_credito', to='maestros.valida', verbose_name='Autorización de Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_valida_vencimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_vencimiento', to='maestros.valida', verbose_name='Autorización de vencimiento'),
        ),
    ]
