# Generated by Django 5.1.1 on 2026-07-20 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_factura_id_valida_limite_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_factura_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Remito_origen', to='ventas.factura', verbose_name='Remito Origen'),
        ),
    ]
