# Generated by Django 5.1.1 on 2026-05-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeading',
            fields=[
                ('id_menu_heading', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Encabezado de Menú')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del encabezado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Encabezado de Menú',
                'verbose_name_plural': 'Encabezados de Menú',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id_menu_item', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Item de Menú')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del item')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la URL (para {% url %})')),
                ('query_params', models.CharField(blank=True, max_length=200, verbose_name='Parámetros de query (ej: ?proceso=actualizar)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Clase del icono (ej: fas fa-book-open)')),
                ('is_collapse', models.BooleanField(default=False, verbose_name='¿Es colapsable? (tiene subitems)')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Orden de aparición')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos permitidos')),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuheading', verbose_name='Encabezado asociado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Item padre')),
            ],
            options={
                'verbose_name': 'Item de Menú',
                'verbose_name_plural': 'Items de Menú',
                'ordering': ['order', 'name'],
            },
        ),
    ]
