# Generated by Django 5.1.1 on 2026-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='orden_acceso_directo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Orden de Acceso Directo'),
        ),
    ]
