# Generated by Django 5.1.1 on 2026-05-05 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='alicuotaiva',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='banco',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.actividad', verbose_name='Actividad*'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='codigoretencion',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='conceptobanco',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='id_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='descuentorevendedor',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='descuentovendedor',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detallevendedorcomision',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='leyenda',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='marketingorigen',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='medidasestados',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='id_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='numero',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='operario',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_alicuota_iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.alicuotaiva', verbose_name='Alíc. IVA'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='productocai',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_cai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
        ),
        migrations.AddField(
            model_name='medidasestados',
            name='id_cai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
        ),
        migrations.AddField(
            model_name='productodeposito',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='productoestado',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto_estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productoestado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='medidasestados',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productoestado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='productofamilia',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productofamilia', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='detallevendedorcomision',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productofamilia', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='descuentovendedor',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productofamilia', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='descuentorevendedor',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productofamilia', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='productomarca',
            name='id_moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='productomarca',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='detallevendedorcomision',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='descuentovendedor',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='descuentorevendedor',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='productominimo',
            name='id_cai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
        ),
        migrations.AddField(
            model_name='productominimo',
            name='id_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productodeposito', verbose_name='Depósito'),
        ),
        migrations.AddField(
            model_name='productominimo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='productomodelo',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomodelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='productostock',
            name='id_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productodeposito', verbose_name='Depósito'),
        ),
        migrations.AddField(
            model_name='productostock',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productostock',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='numero',
            name='id_punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.puntoventa', verbose_name='Punto de Venta'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='productodeposito',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='numero',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal*'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='tipodocumentoidentidad',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_documento_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipodocumentoidentidad', verbose_name='Tipo Doc. Identidad*'),
        ),
        migrations.AddField(
            model_name='tipoiva',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_tipo_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo IVA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo I.V.A.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo de Iva*'),
        ),
        migrations.AddField(
            model_name='tipopercepcionib',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_percepcion_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipopercepcionib', verbose_name='Percepción IB*'),
        ),
        migrations.AddField(
            model_name='tiporetencionib',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_tipo_retencion_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tiporetencionib', verbose_name='Tipo de Retención Ib'),
        ),
        migrations.AddField(
            model_name='valida',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='valida',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal*'),
        ),
        migrations.AddField(
            model_name='valida',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='vendedorcomision',
            name='id_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='vendedorcomision',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='detallevendedorcomision',
            name='id_vendedor_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.vendedorcomision', verbose_name='Vendedor Comisión'),
        ),
        migrations.AddConstraint(
            model_name='descuentovendedor',
            constraint=models.UniqueConstraint(fields=('id_marca', 'id_familia'), name='unique_marca_familia_vendedor', violation_error_message='Ya existe una configuración de descuento para esta combinación de Marca y Familia.'),
        ),
        migrations.AlterUniqueTogether(
            name='descuentovendedor',
            unique_together={('id_marca', 'id_familia')},
        ),
        migrations.AddConstraint(
            model_name='descuentorevendedor',
            constraint=models.UniqueConstraint(fields=('id_marca', 'id_familia'), name='unique_marca_familia_revendedor', violation_error_message='Ya existe una configuración de descuento para esta combinación de Marca y Familia.'),
        ),
        migrations.AlterUniqueTogether(
            name='descuentorevendedor',
            unique_together={('id_marca', 'id_familia')},
        ),
    ]
