# Generated by Django 5.1.1 on 2026-09-07 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronEntreRiosIIBB',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_padron', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha publicación')),
                ('fecha_vigencia_desde', models.DateField(verbose_name='Vigencia desde')),
                ('fecha_vigencia_hasta', models.DateField(verbose_name='Vigencia hasta')),
                ('cuit', models.BigIntegerField(db_index=True, verbose_name='CUIT')),
                ('tipo_contr_insc', models.CharField(blank=True, choices=[('D', 'D'), ('C', 'C'), ('-', 'Sin dato')], max_length=1, null=True, verbose_name='Tipo contribuyente')),
                ('marca_alta_sujeto', models.BooleanField(default=False, verbose_name='Alta sujeto')),
                ('marca_alicuota', models.BooleanField(default=False, verbose_name='Aplica alícuota')),
                ('alicuota_percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Alícuota percepción (%)')),
                ('alicuota_retencion', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Alícuota retención (%)')),
                ('nro_grupo_percepcion', models.CharField(blank=True, default='0', max_length=5, verbose_name='Nro grupo percepción')),
                ('nro_grupo_retencion', models.CharField(blank=True, default='0', max_length=5, verbose_name='Nro grupo retención')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón social')),
                ('id_provincia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'Padrón IIBB - Entre Ríos',
                'verbose_name_plural': 'Padrones IIBB - Entre Ríos',
                'db_table': 'padron_entre_rios',
                'ordering': ['-fecha_vigencia_desde', 'razon_social'],
                'unique_together': {('cuit', 'fecha_vigencia_desde')},
            },
        ),
        migrations.CreateModel(
            name='PadronSantaFeIIBB',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_padron', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha publicación')),
                ('fecha_vigencia_desde', models.DateField(verbose_name='Vigencia desde')),
                ('fecha_vigencia_hasta', models.DateField(verbose_name='Vigencia hasta')),
                ('cuit', models.BigIntegerField(db_index=True, verbose_name='CUIT')),
                ('tipo_contr_insc', models.CharField(blank=True, choices=[('D', 'D'), ('C', 'C'), ('-', 'Sin dato')], max_length=1, null=True, verbose_name='Tipo contribuyente')),
                ('marca_alta_sujeto', models.BooleanField(default=False, verbose_name='Alta sujeto')),
                ('marca_alicuota', models.BooleanField(default=False, verbose_name='Aplica alícuota')),
                ('alicuota_percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Alícuota percepción (%)')),
                ('alicuota_retencion', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Alícuota retención (%)')),
                ('nro_grupo_percepcion', models.CharField(blank=True, default='0', max_length=5, verbose_name='Nro grupo percepción')),
                ('nro_grupo_retencion', models.CharField(blank=True, default='0', max_length=5, verbose_name='Nro grupo retención')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón social')),
                ('id_provincia', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'Padrón IIBB - Santa Fe',
                'verbose_name_plural': 'Padrones IIBB - Santa Fe',
                'db_table': 'padron_santa_fe',
                'ordering': ['-fecha_vigencia_desde', 'razon_social'],
                'unique_together': {('cuit', 'fecha_vigencia_desde')},
            },
        ),
    ]
