# Generated by Django 5.1.1 on 2026-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomarca',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='1ra. Marca'),
        ),
    ]
