# Generated by Django 5.1.1 on 2026-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='stock_clie',
            field=models.BooleanField(blank=True, null=True, verbose_name='stockclie'),
        ),
    ]
