# Generated by Django 5.1.1 on 2026-04-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='nombre_localidad',
            field=models.CharField(max_length=50, verbose_name='Nombre Localidad'),
        ),
    ]
