# Generated by Django 5.1.1 on 2026-09-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_padronentreriosiibb_padronsantafeiibb'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='minimo_percepcion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Mínimo Percepción'),
        ),
        migrations.AlterField(
            model_name='padronentreriosiibb',
            name='id_provincia',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='padronsantafeiibb',
            name='id_provincia',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia'),
        ),
    ]
