# Generated by Django 5.1.1 on 2026-05-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_actividad_id_user_update_alicuotaiva_id_user_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='alicuotaiva',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='codigoretencion',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='conceptobanco',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='descuentorevendedor',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='descuentovendedor',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='detallevendedorcomision',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='leyenda',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='marketingorigen',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='medidasestados',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productocai',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productodeposito',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productoestado',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productofamilia',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productomarca',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productominimo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productomodelo',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='tipoiva',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='valida',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='vendedorcomision',
            name='id_user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
    ]
