# Generated by Django 5.1.1 on 2026-04-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_localidad_nombre_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.BigIntegerField(verbose_name='C.U.I.T.*'),
        ),
    ]
