# Generated by Django 5.1.1 on 2026-04-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_empresa_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='telefono_sucursal',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
