# Generated by Django 5.1.1 on 2026-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_sucursal_telefono_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número doc.*'),
        ),
    ]
