# Generated by Django 5.1.1 on 2026-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_actividad_fcontrol2_alicuotaiva_fcontrol2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pts_costo',
            field=models.IntegerField(default=0, null=True, verbose_name='Pts. costo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pts_premio',
            field=models.IntegerField(default=0, null=True, verbose_name='Pts. premio'),
        ),
    ]
