# Generated by Django 5.1.1 on 2026-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_alter_cliente_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.BigIntegerField(verbose_name='Número'),
        ),
    ]
