# Generated by Django 5.1.1 on 2026-05-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_producto_pts_costo_producto_pts_premio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pts_costo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pts. costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pts_premio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pts. premio'),
        ),
    ]
