# Generated by Django 5.1.1 on 2026-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_producto_pts_costo_alter_producto_pts_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='creditomay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Mayorista'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='creditomin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Minorista'),
        ),
    ]
