# Generated by Django 5.1.1 on 2026-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_numero_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.BigIntegerField(unique=True, verbose_name='C.U.I.T.'),
        ),
    ]
