# Generated by Django 5.1.1 on 2026-05-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_cliente_limite_credito_parametro_creditomay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='creditomay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Mayorista'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creditomin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Minorista'),
        ),
    ]
