# Generated by Django 5.1.1 on 2026-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_empresa_creditomay_empresa_creditomin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sub_cuenta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub Cuenta'),
        ),
    ]
