# Generated by Django 5.1.1 on 2026-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alter_cliente_sub_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_venta',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Cuenta Corriente')], db_index=True, default=True, verbose_name='Condición Venta*'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='creditomay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Reventa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='creditomin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, verbose_name='Crédito Mostrador'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo_venta',
            field=models.CharField(choices=[('M', 'Mostrador'), ('R', 'Revendedor'), ('E', 'E-Commerce')], db_index=True, max_length=1, verbose_name='Tipo'),
        ),
    ]
