# Generated by Django 5.1.1 on 2026-06-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_alter_cliente_condicion_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valida',
            name='compro',
        ),
        migrations.AddField(
            model_name='valida',
            name='id_comprobante_venta',
            field=models.ForeignKey(blank=True, limit_choices_to={'estatus_comprobante_venta': True, 'tipo_comprobante__in': ['REMITO', 'FACTURA', 'NOTA DE CRÉDITO']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comprobante*'),
        ),
    ]
