# Generated by Django 5.1.1 on 2026-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_remove_valida_compro_valida_id_comprobante_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='valida',
            name='motivo',
            field=models.CharField(blank=True, choices=[('VENCIMIENTO', 'Documentos vencidos'), ('LIMITE_CREDITO', 'Límite de crédito excedido')], help_text='Razón por la que se emitió la autorización (Vencimiento o Límite de crédito)', max_length=20, null=True, verbose_name='Motivo de autorización'),
        ),
    ]
