# Generated by Django 5.1.1 on 2026-07-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_valida_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valida',
            name='numero_comprobante',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
