# Generated by Django 5.1.1 on 2026-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jerarquia',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='Z', max_length=1, null=True, verbose_name='Jerarquía'),
        ),
    ]
